mongo-staging:
  image: mongo:3
  volumes:
    - /var/data/mongodb:/data/db
  ports:
    - "27017:27017"
  tags:
    - chuckdemos-production
  autorestart: always
chuckdemos-production:
  image: tutum.co/aknuds1/chuckdemos:latest
  links:
    - mongo-staging:db
  environment:
    - ROOT_URL=https://chuckdemos.com
    - MONGO_URL
    - METEOR_SETTINGS
  tags:
    - chuckdemos-production
  autorestart: always
  ports:
    - "80:80"
logspout-staging:
  image: gliderlabs/logspout
  command: syslog://logs3.papertrailapp.com:19740
  tags:
    - chuckdemos-production
  autorestart: always
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  deployment_strategy: every_node
