mongo-production:
  image: mongo:3
  command: --auth
  volumes:
    - /var/data/mongodb:/data/db
  ports:
    - "27017:27017"
  tags:
    - chuckdemos-production
  autorestart: always
chuckdemos-production:
  image: quay.io/aknuds1/chuckdemos:latest
  links:
    - mongo-production:db
  environment:
    - ROOT_URL=http://chuckdemos.com
    - MONGO_URL
    - METEOR_SETTINGS
  tags:
    - chuckdemos-production
  autorestart: always
  ports:
    - "80:80"
logspout-production:
  image: gliderlabs/logspout
  command: syslog://logs3.papertrailapp.com:19740
  tags:
    - chuckdemos-production
  autorestart: always
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  deployment_strategy: every_node
